//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YummyPizzaAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.Employee_Shift = new HashSet<Employee_Shift>();
        }
    
        public int Employee_ID { get; set; }
        public string Emp_Name { get; set; }
        public string Emp_Surname { get; set; }
        public string Emp_Email { get; set; }
        public string Emp_Address { get; set; }
        public string Emp_Contact { get; set; }
        public Nullable<decimal> Emp_ID_Number { get; set; }
        public Nullable<int> User_ID { get; set; }
        public Nullable<int> Gender_ID { get; set; }
        public Nullable<int> Emp_Type_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employee_Shift> Employee_Shift { get; set; }
        public virtual Employee_Type Employee_Type { get; set; }
        public virtual Gender Gender { get; set; }
        public virtual User User { get; set; }
    }
}
