//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YummyPizzaAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        public int Invoice_ID { get; set; }
        public Nullable<decimal> Subtotal { get; set; }
        public Nullable<decimal> Invoice_Total { get; set; }
        public Nullable<decimal> Amount_Tendered { get; set; }
        public Nullable<decimal> Change { get; set; }
        public Nullable<int> VAT_ID { get; set; }
        public Nullable<int> Order_ID { get; set; }
        public Nullable<int> PMethod_ID { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual PMethod PMethod { get; set; }
        public virtual VAT VAT { get; set; }
    }
}
