//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YummyPizzaAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class PizzaShopEntities : DbContext
    {
        public PizzaShopEntities()
            : base("name=PizzaShopEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Base> Bases { get; set; }
        public virtual DbSet<Base_Price> Base_Price { get; set; }
        public virtual DbSet<Combo> Comboes { get; set; }
        public virtual DbSet<ComboProduct> ComboProducts { get; set; }
        public virtual DbSet<Company> Companies { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Employee_Shift> Employee_Shift { get; set; }
        public virtual DbSet<Employee_Type> Employee_Type { get; set; }
        public virtual DbSet<Extra> Extras { get; set; }
        public virtual DbSet<Extra_Price> Extra_Price { get; set; }
        public virtual DbSet<Gender> Genders { get; set; }
        public virtual DbSet<Invoice> Invoices { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<Order_Status> Order_Status { get; set; }
        public virtual DbSet<Order_Type> Order_Type { get; set; }
        public virtual DbSet<OrderItem> OrderItems { get; set; }
        public virtual DbSet<Pizza> Pizzas { get; set; }
        public virtual DbSet<Pizza_Price> Pizza_Price { get; set; }
        public virtual DbSet<PMethod> PMethods { get; set; }
        public virtual DbSet<Price> Prices { get; set; }
        public virtual DbSet<Shift> Shifts { get; set; }
        public virtual DbSet<Size> Sizes { get; set; }
        public virtual DbSet<Size_Price> Size_Price { get; set; }
        public virtual DbSet<Topping> Toppings { get; set; }
        public virtual DbSet<Topping_Price> Topping_Price { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<VAT> VATs { get; set; }
    
        public virtual ObjectResult<getBaseDetails_Result> getBaseDetails()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getBaseDetails_Result>("getBaseDetails");
        }
    
        public virtual ObjectResult<getExtraDetails_Result> getExtraDetails()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getExtraDetails_Result>("getExtraDetails");
        }
    
        public virtual ObjectResult<getPizzaDetails_Result> getPizzaDetails()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getPizzaDetails_Result>("getPizzaDetails");
        }
    
        public virtual ObjectResult<getSizeDetails_Result> getSizeDetails()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getSizeDetails_Result>("getSizeDetails");
        }
    
        public virtual ObjectResult<getToppingDetails_Result> getToppingDetails()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getToppingDetails_Result>("getToppingDetails");
        }
    
        public virtual ObjectResult<getCombo_Result> getCombo()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getCombo_Result>("getCombo");
        }
    }
}
